# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/3.5.2+b7/argocd-apps.schema.json

# This file configures an ArgoCD app of apps that represent a 
# group of beamline or accelerator IOCs and services. The configuration of the 
# services are in the separate repo indicated by repoURL.

# This repostory only controls which services and which versions of those
# services should be running on the cluster. It is recommended that this repo
# be updated by a CI/CD pipeline or configuration tools only.

project: esq51579
destination:
  name: argus
  namespace: esq51579
source:
  repoURL: https://github.com/marcelldls/t02-services
  targetRevision: 2024.8.3

# list of services to deploy. Each item is of the form:
# - service: service name as it appears in K8S (statefulset/deployment name)
#   targetRevision: optional override for targetRevision above
#   repoURL: optional override for git repo to source the helm chart from
#            the path is always services/<service> within that repo
#   enabled: set to false to stop a service
#   removed: set to true to remove the service from the cluster

services:
  # shared epics services ######################################################
  epics-pvcs:
    enabled: true
  epics-opis:
    enabled: true

  # epics iocs #################################################################
  example-ea-test-01:
    enabled: true
    ec_service: true
    targetRevision: 2024.8.3

  example-ea-test-02:
    ec_service: true
    targetRevision: 2024.8.3
